In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import warnings
warnings.filterwarnings('ignore')
# import data profile report

In [4]:
from google.colab import drive
drive.mount('/content/drive/BX_1203_data.sqlite')
drive.mount('/content/drive/data_Esther1.sqlite')
drive.mount('/content/drive/data_serena.sqlite')
drive.mount('/content/drive/data_testkyle.sqlite')

ValueError: ignored

## Bofe's data --->df1

In [ ]:
import sqlite3

# Connect to the SQLite database
db_path = 'BX_1203_data.sqlite'  # Replace with the actual path to your SQLite database
connection = sqlite3.connect(db_path)

# Create a cursor object to execute SQL queries
cursor = connection.cursor()

# Get the list of tables in the database
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cursor.fetchall()

# Iterate through tables and print column information
for table in tables:
    table_name = table[0]
    print(f"Table: {table_name}")

    # Get column information for each table
    cursor.execute(f"PRAGMA table_info({table_name});")
    columns = cursor.fetchall()

    # Print column information
    for column in columns:
        print(f"  Column: {column[1]}, Type: {column[2]}, Nullable: {'YES' if column[3] else 'NO'}")

# Close the cursor and connection
cursor.close()
connection.close()

con = sqlite3.connect("BX_1203_data.sqlite")

In [ ]:
users_df = pd.read_sql_query("SELECT * from Depop_Data", con)
print(users_df.shape)

DatabaseError: ignored

In [ ]:
item_df = pd.read_sql_query("SELECT * from Depop_Data", con)
print(item_df.shape)

DatabaseError: ignored

In [ ]:
users_df.head()

NameError: ignored

In [ ]:
item_df.head()

,ID,User_id,Sold,Gender,Category,subcategory,size,State,Brand,Colors,Price,Image,Description,Title,Platform,Address,discountedPriceAmount,dateUpdated
0,392925609,36085867,S,male,tops,sweatshirts,L,Used - Excellent,unbranded,"White,Blue",20.00USD,downloads/revivalstudios/f1b12acf780249b5ad4f3...,Vintage 1986 Special Tees Black Sheep Graphic ...,revivalstudios vintage 1986 special tees black,Depop,"Colorado Springs, United States",None,2023-11-30T23:08:04.320471Z
1,392961853,36085867,S,female,tops,sweatshirts,L,Used - Excellent,morning-sun,Navy,20.00USD,downloads/revivalstudios/9025cbbd01924c8d9b1ea...,Vintage Women 90s Morning Sun Graphic Flower S...,revivalstudios vintage women 90s morning sun,Depop,"Colorado Springs, United States",None,2023-11-30T21:49:31.252467Z
2,392960271,36085867,S,female,tops,sweatshirts,XXL,Used - Excellent,lee,Grey,15.00USD,downloads/revivalstudios/df7948978b5c46f0a917e...,Vintage Women 90s Lee Hockey Mom Embroidered S...,revivalstudios vintage women 90s lee hockey,Depop,"Colorado Springs, United States",None,2023-11-30T21:41:52.574275Z
3,392958800,36085867,S,male,tops,sweatshirts,M,Used - Excellent,unbranded,,20.00USD,downloads/revivalstudios/3a531bf876d14a878d0ce...,Vintage 90s Teejays Boston Graphic Sweatshirt ...,revivalstudios vintage 90s teejays boston graphic,Depop,"Colorado Springs, United States",None,2023-11-30T21:33:44.702803Z
4,392928042,36085867,S,male,tops,sweatshirts,L,Used - Excellent,tultex,"Red,Multi",20.00USD,downloads/revivalstudios/5dce3ed09d5f490b99f38...,Vintage 90s Tultex Sports Bear Graphic SZ L 23...,revivalstudios vintage 90s tultex sports bear,Depop,"Colorado Springs, United States",None,2023-11-30T18:38:50.952229Z

In [ ]:
# mrege two dataframes
df1 = pd.merge(users_df, item_df, on='User_id', how='inner')
df1.head()

,Username,User_id,bio,first_name,followers,following,initials,items_sold,last_name,last_seen,...,Brand,Colors,Price,Image,Description,Title,Platform,Address,discountedPriceAmount,dateUpdated
0,revivalstudios,36085867,b'Lost Clothing that needs revival \xf0\x9f\x9...,b'Revival Studios',886,59,b'R',600,b'',2023-12-01T02:09:41.965076Z,...,unbranded,"White,Blue",20.00USD,downloads/revivalstudios/f1b12acf780249b5ad4f3...,Vintage 1986 Special Tees Black Sheep Graphic ...,revivalstudios vintage 1986 special tees black,Depop,"Colorado Springs, United States",None,2023-11-30T23:08:04.320471Z
1,revivalstudios,36085867,b'Lost Clothing that needs revival \xf0\x9f\x9...,b'Revival Studios',886,59,b'R',600,b'',2023-12-01T02:09:41.965076Z,...,morning-sun,Navy,20.00USD,downloads/revivalstudios/9025cbbd01924c8d9b1ea...,Vintage Women 90s Morning Sun Graphic Flower S...,revivalstudios vintage women 90s morning sun,Depop,"Colorado Springs, United States",None,2023-11-30T21:49:31.252467Z
2,revivalstudios,36085867,b'Lost Clothing that needs revival \xf0\x9f\x9...,b'Revival Studios',886,59,b'R',600,b'',2023-12-01T02:09:41.965076Z,...,lee,Grey,15.00USD,downloads/revivalstudios/df7948978b5c46f0a917e...,Vintage Women 90s Lee Hockey Mom Embroidered S...,revivalstudios vintage women 90s lee hockey,Depop,"Colorado Springs, United States",None,2023-11-30T21:41:52.574275Z
3,revivalstudios,36085867,b'Lost Clothing that needs revival \xf0\x9f\x9...,b'Revival Studios',886,59,b'R',600,b'',2023-12-01T02:09:41.965076Z,...,unbranded,,20.00USD,downloads/revivalstudios/3a531bf876d14a878d0ce...,Vintage 90s Teejays Boston Graphic Sweatshirt ...,revivalstudios vintage 90s teejays boston graphic,Depop,"Colorado Springs, United States",None,2023-11-30T21:33:44.702803Z
4,revivalstudios,36085867,b'Lost Clothing that needs revival \xf0\x9f\x9...,b'Revival Studios',886,59,b'R',600,b'',2023-12-01T02:09:41.965076Z,...,tultex,"Red,Multi",20.00USD,downloads/revivalstudios/5dce3ed09d5f490b99f38...,Vintage 90s Tultex Sports Bear Graphic SZ L 23...,revivalstudios vintage 90s tultex sports bear,Depop,"Colorado Springs, United States",None,2023-11-30T18:38:50.952229Z

In [ ]:
df1.shape

(122414, 32)

In [ ]:
df1.columns

Index(['Username', 'User_id', 'bio', 'first_name', 'followers', 'following',
       'initials', 'items_sold', 'last_name', 'last_seen', 'Avatar',
       'reviews_rating', 'reviews_total', 'verified', 'website', 'ID', 'Sold',
       'Gender', 'Category', 'subcategory', 'size', 'State', 'Brand', 'Colors',
       'Price', 'Image', 'Description', 'Title', 'Platform', 'Address',
       'discountedPriceAmount', 'dateUpdated'],
      dtype='object')

In [ ]:
# check if all the verified data is false
df1['verified'].value_counts()

True     77135
False    45279
Name: verified, dtype: int64

## Esther's data --->df2

In [ ]:
# Connect to the SQLite database
db_path_2 = 'data_Esther1.sqlite'  # Replace with the actual path to your SQLite database
con = sqlite3.connect(db_path_2)

In [ ]:
users_df_2 = pd.read_sql_query("SELECT * from Depop_Users", con)
print(users_df_2.shape)

(50, 15)

In [ ]:
item_df_2 = pd.read_sql_query("SELECT * from Depop_Data", con)
print(item_df_2.shape)

(4719, 18)

In [ ]:
df2 = pd.merge(users_df_2, item_df_2, on='User_id', how='inner')
df2.head()

,Username,User_id,bio,first_name,followers,following,initials,items_sold,last_name,last_seen,...,Brand,Colors,Price,Image,Description,Title,Platform,Address,discountedPriceAmount,dateUpdated
0,anoterosllc,43283981,b'',b'Anoteros',0,0,b'AL',4,b'LLC',2023-11-30T19:08:31.066331Z,...,the-north-face,,200.00USD,None,🛩️ Ships same day \n🤝 NWT guaranteed \nThe Nor...,anoterosllc ships same day 5a9d,Depop,"Bothell, United States",None,2023-08-31T05:21:54.179553Z
1,anoterosllc,43283981,b'',b'Anoteros',0,0,b'AL',4,b'LLC',2023-11-30T19:08:31.066331Z,...,the-north-face,Black,160.00USD,None,🛩️ Ships same day \n🤝 NWT guaranteed \nThe Nor...,anoterosllc ships same day f355,Depop,"Bothell, United States",None,2023-08-31T05:18:15.502881Z
2,anoterosllc,43283981,b'',b'Anoteros',0,0,b'AL',4,b'LLC',2023-11-30T19:08:31.066331Z,...,the-north-face,,230.00USD,None,🛩️ Ships same day \n🤝 NWT guaranteed \nThe Nor...,anoterosllc ships same day e20a,Depop,"Bothell, United States",None,2023-08-31T05:14:13.215009Z
3,anoterosllc,43283981,b'',b'Anoteros',0,0,b'AL',4,b'LLC',2023-11-30T19:08:31.066331Z,...,the-north-face,Black,240.00USD,None,🛩️ Ships same day \n🤝 NWT guaranteed \nThe Nor...,anoterosllc ships same day 5b2b,Depop,"Bothell, United States",None,2023-08-31T05:13:02.663956Z
4,anoterosllc,43283981,b'',b'Anoteros',0,0,b'AL',4,b'LLC',2023-11-30T19:08:31.066331Z,...,the-north-face,Black,230.00USD,None,🛩️ Ships same day \n🤝 NWT guaranteed \nThe Nor...,anoterosllc ships same day,Depop,"Bothell, United States",None,2023-08-31T05:11:14.182433Z

## Serena data -->df3

In [ ]:
# Connect to the SQLite database
db_path_3 = 'data_serena.sqlite'  # Replace with the actual path to your SQLite database
con = sqlite3.connect(db_path_3)

In [ ]:
users_df_3 = pd.read_sql_query("SELECT * from Depop_Users", con)
print(users_df_3.shape)

(37, 15)

In [ ]:
item_df_3 = pd.read_sql_query("SELECT * from Depop_Data", con)
print(item_df_3.shape)

(34244, 18)

In [ ]:
df3 = pd.merge(users_df_3, item_df_3, on='User_id', how='inner')
df3.head()

,Username,User_id,bio,first_name,followers,following,initials,items_sold,last_name,last_seen,...,Brand,Colors,Price,Image,Description,Title,Platform,Address,discountedPriceAmount,dateUpdated
0,walkman,4565848,b'',b'Ellis',22,38,b'ED',11,b'Dee',2023-12-02T00:42:01.822496Z,...,champion,Grey,16.00USD,None,Mens Small Champion Hoodie Grey Camo. Few smal...,walkman mens small champion hoodie grey,Depop,"Henrico, United States",None,2023-12-01T05:17:11.008677Z
1,walkman,4565848,b'',b'Ellis',22,38,b'ED',11,b'Dee',2023-12-02T00:42:01.822496Z,...,columbia-sportswear,Purple,35.00USD,None,"Vintage Columbia Reversible Jacket, Mens Mediu...",walkman vintage columbia reversible jacket mens,Depop,"Henrico, United States",None,2023-11-30T23:03:18.337924Z
2,walkman,4565848,b'',b'Ellis',22,38,b'ED',11,b'Dee',2023-12-02T00:42:01.822496Z,...,polo-ralph-lauren,Navy,5.00USD,None,Mens Large. Polo Ralph Lauren Pajama Pant Bott...,walkman mens large polo ralph lauren,Depop,"Henrico, United States",None,2023-11-30T22:03:58.733736Z
3,walkman,4565848,b'',b'Ellis',22,38,b'ED',11,b'Dee',2023-12-02T00:42:01.822496Z,...,old-navy,"White,Blue",8.00USD,None,Mens Medium Short Sleeve Button Down Shirt Old...,walkman mens medium short sleeve button 0afd,Depop,"Henrico, United States",None,2023-11-30T22:00:56.471542Z
4,walkman,4565848,b'',b'Ellis',22,38,b'ED',11,b'Dee',2023-12-02T00:42:01.822496Z,...,unbranded,,6.00USD,None,Mens Medium Short Sleeve Button Down Shirt Kni...,walkman mens medium short sleeve button,Depop,"Henrico, United States",None,2023-11-30T21:59:25.877129Z

## Merge df1 df2 and df3

In [ ]:
# check shape
print(df1.shape)
print(df2.shape)
print(df3.shape)

(122414, 32)
(4768, 32)
(34244, 32)

In [ ]:
# concat data
df_all = pd.concat([df1,df2,df3])

In [ ]:
print(df_all.shape)

(161426, 32)

## Merge the df_all with annotated data

In [ ]:
# read annotated df
df_ann_1 = pd.read_csv('Fake user annotation - Sheet1.csv')
df_ann_2 = pd.read_csv('Fake user annotation - Scraped users.csv')

In [ ]:
df_ann_1.head(20)

,Username,Type,"Type 1 = fake user, Type 0 = real user",Inputted by,Verified by,Reason,verification notes
0,thriftlu,clothing,0,Serena,NaN,NaN,NaN
1,consciousbrat,clothing,0,Esther,NaN,NaN,NaN
2,joyyw,clothing,0,Esther,NaN,NaN,NaN
3,gr00vysushi,clothing,NaN,Esther,NaN,NaN,NaN
4,crystallxoxo,clothing,NaN,Esther,NaN,NaN,NaN
5,thuggathuggababy,clothing,NaN,Esther,NaN,NaN,NaN
7,lauraggrace,clothing,1,Esther,Kylie,Bad review w stock images,NaN
8,savannahdunrod,clothing,0,Esther,NaN,NaN,NaN
9,tiana_parker,clothing,0,Esther,NaN,ig profile has her depop,NaN
10,cassielavender,clothing,0,Esther,NaN,NaN,NaN
11,sahoon,clothing,0,Esther,NaN,NaN,NaN
12,idkdontask,clothing,0,Esther,NaN,NaN,NaN
13,nellyworethis,clothing,0,Esther,NaN,NaN,NaN
14,gracus_fellacus,clothing,0,Esther,NaN,NaN,NaN
15,pamelaannpaulshock,clothing,0,Esther,NaN,NaN,NaN
16,shopapril2000,clothing,0,Esther,NaN,NaN,NaN
17,luuvbree,clothing,0,Esther,NaN,NaN,NaN
18,jimmylawson,clothing,1,Esther,Kylie,"Double listing, high end brands at low price",NaN
19,abigale721,clothing,0,Esther,NaN,poshmark account has double listed posts,NaN
20,easymoneysniperustin,clothing,0,Esther,NaN,background has similar themes,NaN

In [ ]:
df_ann_2.head(20)

,Username,Type,Serena's classification,Unnamed: 3,who is scraping,Verified by,Reason,verification notes,Scraping notes
0,supremefj94,NaN,0.0,NaN,Bofei,Esther,NaN,NaN,NaN
1,skinfurther,NaN,1.0,NaN,Bofei,Esther,"many negative reviews, never received items",NaN,NaN
2,gothmfswag,NaN,0.0,NaN,Bofei,NaN,NaN,NaN,NaN
3,acevintageoutpost,NaN,0.0,NaN,Bofei,NaN,NaN,NaN,NaN
4,codylee1337,NaN,0.0,NaN,Bofei,NaN,NaN,NaN,NaN
5,homeless_vtg,NaN,0.0,NaN,Bofei,NaN,NaN,NaN,NaN
6,b707vintage,NaN,1.0,NaN,Bofei,Esther,NaN,NaN,NaN
7,aidxnbxdley,NaN,0.0,NaN,Bofei,NaN,NaN,NaN,NaN
8,bam01,NaN,0.0,NaN,Bofei,NaN,NaN,NaN,NaN
9,215winny,NaN,0.0,NaN,Bofei,NaN,NaN,NaN,NaN
10,majorityruleclothes,NaN,0.0,NaN,Bofei,NaN,NaN,NaN,NaN
11,vtguni,NaN,0.0,NaN,Bofei,NaN,NaN,NaN,NaN
12,onseam,NaN,0.0,NaN,Bofei,NaN,NaN,NaN,NaN
13,camphalfblood,NaN,1.0,NaN,Bofei,Esther,unsure,NaN,NaN
14,cheweyap,NaN,0.0,NaN,Bofei,NaN,NaN,NaN,NaN
15,revivalstudios,NaN,0.0,NaN,Bofei,NaN,NaN,NaN,NaN
16,snyder_lucy,NaN,0.0,NaN,Bofei,NaN,NaN,NaN,NaN
17,clothesfromo,NaN,0.0,NaN,Bofei,NaN,NaN,NaN,NaN
18,rileydowns06,NaN,0.0,NaN,Bofei,NaN,NaN,NaN,NaN
19,idprollypass,NaN,0.0,NaN,Bofei,NaN,NaN,NaN,NaN

In [ ]:
# drop na in both df
df_ann_1.dropna(inplace = True, subset = ['Username'])
df_ann_2.dropna(inplace = True, subset = ['Username', "Serena's classification"])

In [ ]:
df_ann_1 = df_ann_1[['Username', 'Type 1 = fake user, Type 0 = real user']]
df_ann_2 = df_ann_2[['Username', "Serena's classification"]]

In [ ]:
# rename columns
column_rename_mapping_1 = {
    'Username': 'Username',
    'Type 1 = fake user, Type 0 = real user': 'Type',
}

column_rename_mapping_2 = {
    'Username': 'Username',
    "Serena's classification": 'Type',
}
df_ann_1 = df_ann_1.rename(columns=column_rename_mapping_1)
df_ann_2 = df_ann_2.rename(columns=column_rename_mapping_2)
print(df_ann_1.columns, df_ann_2.columns)

Index(['Username', 'Type'], dtype='object') Index(['Username', 'Type'], dtype='object')

In [ ]:
print(df_ann_1.shape)
print(df_ann_2.shape)

(76, 2)
(160, 2)

In [ ]:
# concat two df
df_ann = pd.concat([df_ann_1, df_ann_2])
print(df_ann.shape)

(236, 2)

In [ ]:
df_ann

                  Username  Type
0                 thriftlu     0
1            consciousbrat     0
2                    joyyw     0
7              lauraggrace     1
8           savannahdunrod     0
..                     ...   ...
158  anomaly_curatedbycris     0
159         rachelkjhgfdsa     0
160             mb_thrifts     0
161               lastcall     0
162            punkhamster     0

[231 rows x 2 columns]

In [ ]:
# convert tpye to string
df_ann['Type'] = df_ann['Type'].astype(str)

In [ ]:
df_ann.dtypes

Username    object
Type        object
dtype: object

In [ ]:
# remove all non numerical value in Type column
df_ann = df_ann[(df_ann['Type'] == '0') | (df_ann['Type'] == '1')|
                (df_ann['Type'] == '0.0') | (df_ann['Type'] == '1.0')]
print(df_ann.shape)

(231, 2)

In [ ]:
df_ann['Type'] = df_ann['Type'].apply(lambda x: 1 if x in ['1', '1.0'] else 0)

In [ ]:
df_ann['Type'].value_counts()

0    215
1     16
Name: Type, dtype: int64

In [ ]:
df_all['Type'] = 0
df_all.columns

Index(['Username', 'User_id', 'bio', 'first_name', 'followers', 'following',
       'initials', 'items_sold', 'last_name', 'last_seen', 'Avatar',
       'reviews_rating', 'reviews_total', 'verified', 'website', 'ID', 'Sold',
       'Gender', 'Category', 'subcategory', 'size', 'State', 'Brand', 'Colors',
       'Price', 'Image', 'Description', 'Title', 'Platform', 'Address',
       'discountedPriceAmount', 'dateUpdated', 'Type'],
      dtype='object')

In [ ]:
# Merge df_all and df_ann based on 'Username'
merged_df = pd.merge(df_all, df_ann[['Username', 'Type']], on='Username', how='left')

# Update 'Type' column in df_all based on the values from df_ann
merged_df['Type_x'] = merged_df['Type_y'].fillna(merged_df['Type_x']).astype(int)

# Drop the additional 'Type_y' column
merged_df = merged_df.drop(columns=['Type_y'])

# Rename the updated 'Type_x' column back to 'Type'
merged_df = merged_df.rename(columns={'Type_x': 'Type'})

print(merged_df.shape)

(162590, 33)

In [ ]:
merged_df.head()

,Username,User_id,bio,first_name,followers,following,initials,items_sold,last_name,last_seen,...,Colors,Price,Image,Description,Title,Platform,Address,discountedPriceAmount,dateUpdated,Type
0,revivalstudios,36085867,b'Lost Clothing that needs revival \xf0\x9f\x9...,b'Revival Studios',886,59,b'R',600,b'',2023-12-01T02:09:41.965076Z,...,"White,Blue",20.00USD,downloads/revivalstudios/f1b12acf780249b5ad4f3...,Vintage 1986 Special Tees Black Sheep Graphic ...,revivalstudios vintage 1986 special tees black,Depop,"Colorado Springs, United States",None,2023-11-30T23:08:04.320471Z,0
1,revivalstudios,36085867,b'Lost Clothing that needs revival \xf0\x9f\x9...,b'Revival Studios',886,59,b'R',600,b'',2023-12-01T02:09:41.965076Z,...,Navy,20.00USD,downloads/revivalstudios/9025cbbd01924c8d9b1ea...,Vintage Women 90s Morning Sun Graphic Flower S...,revivalstudios vintage women 90s morning sun,Depop,"Colorado Springs, United States",None,2023-11-30T21:49:31.252467Z,0
2,revivalstudios,36085867,b'Lost Clothing that needs revival \xf0\x9f\x9...,b'Revival Studios',886,59,b'R',600,b'',2023-12-01T02:09:41.965076Z,...,Grey,15.00USD,downloads/revivalstudios/df7948978b5c46f0a917e...,Vintage Women 90s Lee Hockey Mom Embroidered S...,revivalstudios vintage women 90s lee hockey,Depop,"Colorado Springs, United States",None,2023-11-30T21:41:52.574275Z,0
3,revivalstudios,36085867,b'Lost Clothing that needs revival \xf0\x9f\x9...,b'Revival Studios',886,59,b'R',600,b'',2023-12-01T02:09:41.965076Z,...,,20.00USD,downloads/revivalstudios/3a531bf876d14a878d0ce...,Vintage 90s Teejays Boston Graphic Sweatshirt ...,revivalstudios vintage 90s teejays boston graphic,Depop,"Colorado Springs, United States",None,2023-11-30T21:33:44.702803Z,0
4,revivalstudios,36085867,b'Lost Clothing that needs revival \xf0\x9f\x9...,b'Revival Studios',886,59,b'R',600,b'',2023-12-01T02:09:41.965076Z,...,"Red,Multi",20.00USD,downloads/revivalstudios/5dce3ed09d5f490b99f38...,Vintage 90s Tultex Sports Bear Graphic SZ L 23...,revivalstudios vintage 90s tultex sports bear,Depop,"Colorado Springs, United States",None,2023-11-30T18:38:50.952229Z,0

In [ ]:
# count type distributions
merged_df['Type'].value_counts()

0    154837
1      7753
Name: Type, dtype: int64

In [ ]:
merged_df.to_csv('merged_df.csv')

## Bag of Words

In [ ]:
merged_df = pd.read_csv('merged_df.csv')

In [ ]:
# use the bag of word to find the most common words in the description
from sklearn.feature_extraction.text import CountVectorizer
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
import pandas as pd
from collections import Counter
import string

In [ ]:
merged_df['Description'].head()

0    Vintage 1986 Special Tees Black Sheep Graphic ...
1    Vintage Women 90s Morning Sun Graphic Flower S...
2    Vintage Women 90s Lee Hockey Mom Embroidered S...
3    Vintage 90s Teejays Boston Graphic Sweatshirt ...
4    Vintage 90s Tultex Sports Bear Graphic SZ L 23...
Name: Description, dtype: object

*One hot for unique strings(only keep 1000 most common strings)*

In [ ]:
# Combine all descriptions into a single string
all_descriptions = ' '.join(merged_df['Description'].astype(str).values)

# Remove punctuation and convert to lowercase
translator = str.maketrans('', '', string.punctuation)
cleaned_text = all_descriptions.translate(translator).lower()

# Split the text into words
words = cleaned_text.split()

# Count the occurrences of each word
word_counts = Counter(words)

# Get the 1000 most common words
most_common_words = word_counts.most_common(1000)
most_common_words_list = [word for word, _ in most_common_words]

In [ ]:
most_common_words_list[:10]

['vintage', 'and', 'size', 'the', 'a', 'condition', 'to', 'for', 'is', 'in']

In [ ]:
# make all unique words as columns in a dataframe and lable if the word is in the description
merged_df[most_common_words_list] = merged_df['Description'].apply(lambda x: pd.Series([1 if word in x else 0 for word in most_common_words_list]))

merged_df.head()

,Unnamed: 0,Username,User_id,bio,first_name,followers,following,initials,items_sold,last_name,...,label,rocawear,drawstring,📥,y2kstyle,suede,south,approx,cybergrunge,95
0,0,revivalstudios,36085867,b'Lost Clothing that needs revival \xf0\x9f\x9...,b'Revival Studios',886,59,b'R',600,b'',...,0,0,0,0,0,0,0,0,0,0
1,1,revivalstudios,36085867,b'Lost Clothing that needs revival \xf0\x9f\x9...,b'Revival Studios',886,59,b'R',600,b'',...,0,0,0,0,0,0,0,0,0,0
2,2,revivalstudios,36085867,b'Lost Clothing that needs revival \xf0\x9f\x9...,b'Revival Studios',886,59,b'R',600,b'',...,0,0,0,0,0,0,0,0,0,0
3,3,revivalstudios,36085867,b'Lost Clothing that needs revival \xf0\x9f\x9...,b'Revival Studios',886,59,b'R',600,b'',...,0,0,0,0,0,0,0,0,0,0
4,4,revivalstudios,36085867,b'Lost Clothing that needs revival \xf0\x9f\x9...,b'Revival Studios',886,59,b'R',600,b'',...,0,0,0,0,0,0,0,0,0,0

In [ ]:
merged_df.shape

(162590, 1033)

In [ ]:
merged_df.columns[:50].tolist()

['Unnamed: 0',
 'Username',
 'User_id',
 'bio',
 'first_name',
 'followers',
 'following',
 'initials',
 'items_sold',
 'last_name',
 'last_seen',
 'Avatar',
 'reviews_rating',
 'reviews_total',
 'verified',
 'website',
 'ID',
 'Sold',
 'Gender',
 'Category',
 'subcategory',
 'size',
 'State',
 'Brand',
 'Colors',
 'Price',
 'Image',
 'Description',
 'Title',
 'Platform',
 'Address',
 'discountedPriceAmount',
 'dateUpdated',
 'Type',
 'vintage',
 'and',
 'the',
 'a',
 'condition',
 'to',
 'for',
 'is',
 'in',
 'are',
 'of',
 'y2k',
 '90s',
 'with',
 'on',
 'pit']

In [ ]:
merged_df.to_csv('bow_df.csv')